(function(){var h={},mt={},c={id:"f80177df4b25b2662225b26a02a32ab8",dm:["bootstrapmb.com"],js:"tongji.baidu.com/hm-web/js/",etrk:[],cetrk:[],cptrk:[],icon:'',ctrk:true,align:0,nv:-1,vdur:1800000,age:31536000000,rec:0,rp:[],trust:0,vcard:0,qiao:0,lxb:0,kbtrk:0,pt:0,spa:0,aet:'',hca:'60958490CC0FCEC1',conv:0,med:0,cvcc:'',cvcf:[],apps:''};var s=void 0,v=!0,w=null,x=!1;mt.cookie={};mt.cookie.set=function(a,b,g){var d;g.Q&&(d=new Date,d.setTime(d.getTime()+g.Q));document.cookie=a+"="+b+(g.domain?"; domain="+g.domain:"")+(g.path?"; path="+g.path:"")+(d?"; expires="+d.toGMTString():"")+(g.Kc?"; secure":"")};mt.cookie.get=function(a){return(a=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie))?a[2]:w};
mt.cookie.lc=function(a,b){try{var g="Hm_ck_"+ +new Date;mt.cookie.set(g,"is-cookie-enabled",{domain:a,path:b,Q:s});var d="is-cookie-enabled"===mt.cookie.get(g)?"1":"0";mt.cookie.set(g,"",{domain:a,path:b,Q:-1});return d}catch(e){return"0"}};mt.lang={};mt.lang.d=function(a,b){return"[object "+b+"]"==={}.toString.call(a)};mt.lang.Ya=function(a){return mt.lang.d(a,"Number")&&isFinite(a)};mt.lang.G=function(a){return mt.lang.d(a,"String")};mt.lang.isArray=function(a){return mt.lang.d(a,"Array")};
mt.lang.h=function(a){return a.replace?a.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):a};mt.lang.trim=function(a){return a.replace(/^\s+|\s+$/g,"")};mt.lang.F=function(a,b){var g=x;if(a==w||!mt.lang.d(a,"Array")||b===s)return g;if(Array.prototype.indexOf)g=-1!==a.indexOf(b);else for(var d=0;d<a.length;d++)if(a[d]===b){g=v;break}return g};mt.url={};mt.url.m=function(a,b){var g=a.match(RegExp("(^|&|\\?|#)("+b+")=([^&#]*)(&|$|#)",""));return g?g[3]:w};
mt.url.Gc=function(a){return(a=a.match(/^(https?:)\/\//))?a[1]:w};mt.url.Pb=function(a){return(a=a.match(/^(https?:\/\/)?([^\/\?#]*)/))?a[2].replace(/.*@/,""):w};mt.url.K=function(a){return(a=mt.url.Pb(a))?a.replace(/:\d+$/,""):a};mt.url.Ca=function(a){return(a=a.match(/^(https?:\/\/)?[^\/]*(.*)/))?a[2].replace(/[\?#].*/,"").replace(/^$/,"/"):w};
(function(){var a=mt.lang,b=mt.url;mt.f={};mt.f.Ra=function(a){return document.getElementById(a)};mt.f.Aa=function(a){if(!a)return w;try{a=String(a);if(0===a.indexOf("!HMCQ!"))return a;if(0===a.indexOf("!HMCC!"))return document.querySelector(a.substring(6,a.length));for(var d=a.split(">"),e=document.body,b=d.length-1;0<=b;b--)if(-1<d[b].indexOf("#")){var f=d[b].split("#")[1];(e=document.getElementById(f))||(e=document.getElementById(decodeURIComponent(f)));d=d.splice(b+1,d.length-(b+1));break}for(a=
0;e&&a<d.length;){var m=String(d[a]).toLowerCase();if(!("html"===m||"body"===m)){var b=0,q=d[a].match(/\[(\d+)\]/i),f=[];if(q)b=q[1]-1,m=m.split("[")[0];else if(1!==e.childNodes.length){for(var t=0,r=0,n=e.childNodes.length;r<n;r++){var u=e.childNodes[r];1===u.nodeType&&u.nodeName.toLowerCase()===m&&t++;if(1<t)return w}if(1!==t)return w}for(t=0;t<e.childNodes.length;t++)1===e.childNodes[t].nodeType&&e.childNodes[t].nodeName.toLowerCase()===m&&f.push(e.childNodes[t]);if(!f[b])return w;e=f[b]}a++}return e}catch(k){return w}};
mt.f.Ca=function(a,d){var e=[],b=[];if(!a)return b;for(;a.parentNode!=w;){for(var f=0,m=0,q=a.parentNode.childNodes.length,t=0;t<q;t++){var r=a.parentNode.childNodes[t];if(r.nodeName===a.nodeName&&(f++,r===a&&(m=f),0<m&&1<f))break}if((q=""!==a.id)&&d){e.unshift("#"+encodeURIComponent(a.id));break}else q&&(q="#"+encodeURIComponent(a.id),q=0<e.length?q+">"+e.join(">"):q,b.push(q)),e.unshift(encodeURIComponent(String(a.nodeName).toLowerCase())+(1<f?"["+m+"]":""));a=a.parentNode}b.push(e.join(">"));return b};
mt.f.ea=function(a){return(a=mt.f.Ca(a,v))&&a.length?String(a[0]):""};mt.f.Tb=function(a){return mt.f.Ca(a,x)};mt.f.Sa=function(a){var d;for(d="A";(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==d)return a;return w};mt.f.Lb=function(a){return 9===a.nodeType?a:a.ownerDocument||a.document};mt.f.Ta=function(a){var d={top:0,left:0};if(!a)return d;var b=mt.f.Lb(a).documentElement;"undefined"!==typeof a.getBoundingClientRect&&(d=a.getBoundingClientRect());return{top:d.top+(window.pageYOffset||b.scrollTop)-
(b.clientTop||0),left:d.left+(window.pageXOffset||b.scrollLeft)-(b.clientLeft||0)}};mt.f.getAttribute=function(a,d){var b=a.getAttribute&&a.getAttribute(d)||w;if(!b&&a.attributes&&a.attributes.length)for(var l=a.attributes,f=l.length,m=0;m<f;m++)l[m].nodeName===d&&(b=l[m].nodeValue);return b};mt.f.T=function(a){var d="document";a.tagName!==s&&(d=a.tagName);return d.toLowerCase()};mt.f.Wb=function(b){var d="";b.textContent?d=a.trim(b.textContent):b.innerText&&(d=a.trim(b.innerText));d&&(d=d.replace(/\s+/g,
" ").substring(0,255));return d};mt.f.S=function(g,d){var e;a.G(g)&&0===String(g).indexOf("!HMCQ!")?(e=String(g),e=b.m(document.location.href,e.substring(6,e.length))):a.G(g)||(e=mt.f.T(g),"input"===e&&d&&("button"===g.type||"submit"===g.type)?e=a.trim(g.value)||"":"input"===e&&!d&&"password"!==g.type?e=a.trim(g.value)||"":"img"===e?(e=mt.f.getAttribute,e=e(g,"alt")||e(g,"title")||e(g,"src")):e="body"===e||"html"===e?["(hm-default-content-for-",e,")"].join(""):mt.f.Wb(g));return String(e||"").substring(0,
255)};(function(){(mt.f.eb=function(){function a(){if(!a.ia){a.ia=v;for(var d=0,b=l.length;d<b;d++)l[d]()}}function d(){try{document.documentElement.doScroll("left")}catch(b){setTimeout(d,1);return}a()}var b=x,l=[],f;document.addEventListener?f=function(){document.removeEventListener("DOMContentLoaded",f,x);a()}:document.attachEvent&&(f=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",f),a())});(function(){if(!b)if(b=v,"complete"===document.readyState)a.ia=v;
else if(document.addEventListener)document.addEventListener("DOMContentLoaded",f,x),window.addEventListener("load",a,x);else if(document.attachEvent){document.attachEvent("onreadystatechange",f);window.attachEvent("onload",a);var m=x;try{m=window.frameElement==w}catch(q){}document.documentElement.doScroll&&m&&d()}})();return function(d){a.ia?d():l.push(d)}}()).ia=x})();return mt.f})();mt.event={};
mt.event.e=function(a,b,g){a.attachEvent?a.attachEvent("on"+b,function(d){g.call(a,d)}):a.addEventListener&&a.addEventListener(b,g,x)};mt.event.preventDefault=function(a){a.preventDefault?a.preventDefault():a.returnValue=x};
(function(){var a=mt.event;mt.g={};mt.g.ga=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.g.Qb=function(){if(document.documentMode)return document.documentMode;var a=/msie (\d+\.\d+)/i.exec(navigator.userAgent);return a?+a[1]||0:0};mt.g.jc=function(){try{return!!navigator.userAgent.match(/safari/i)&&!navigator.userAgent.match(/chrome/i)&&"undefined"!==typeof document.body.style.webkitFilter&&!window.chrome}catch(a){return x}};mt.g.cookieEnabled=navigator.cookieEnabled;mt.g.javaEnabled=navigator.javaEnabled();
mt.g.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.g.qc=(window.screen.width||0)+"x"+(window.screen.height||0);mt.g.colorDepth=window.screen.colorDepth||0;mt.g.U=function(){var a;a=a||document;return parseInt(window.pageYOffset||a.documentElement.scrollTop||a.body&&a.body.scrollTop||0,10)};mt.g.L=function(){var a=document;return parseInt(window.innerHeight||a.documentElement.clientHeight||a.body&&a.body.clientHeight||0,10)};mt.g.Ec=
0;mt.g.Yb=function(){var a=document;return parseInt(window.innerWidth||a.documentElement.clientWidth||a.body.offsetWidth||0,10)};mt.g.orientation=0;(function(){function b(){var a=0;window.orientation!==s&&(a=window.orientation);screen&&(screen.orientation&&screen.orientation.angle!==s)&&(a=screen.orientation.angle);mt.g.orientation=a;mt.g.Ec=mt.g.Yb()}b();a.e(window,"orientationchange",b)})();return mt.g})();mt.o={};mt.o.parse=function(a){return(new Function("return ("+a+")"))()};
mt.o.stringify=function(){function a(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var d=g[a];if(d)return d;d=a.charCodeAt();return"\\u00"+Math.floor(d/16).toString(16)+(d%16).toString(16)}));return'"'+a+'"'}function b(a){return 10>a?"0"+a:a}var g={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(d){switch(typeof d){case "undefined":return"undefined";case "number":return isFinite(d)?String(d):"null";case "string":return a(d);case "boolean":return String(d);
default:if(d===w)return"null";if(d instanceof Array){var e=["["],g=d.length,f,m,q;for(m=0;m<g;m++)switch(q=d[m],typeof q){case "undefined":case "function":case "unknown":break;default:f&&e.push(","),e.push(mt.o.stringify(q)),f=1}e.push("]");return e.join("")}if(d instanceof Date)return'"'+d.getFullYear()+"-"+b(d.getMonth()+1)+"-"+b(d.getDate())+"T"+b(d.getHours())+":"+b(d.getMinutes())+":"+b(d.getSeconds())+'"';f=["{"];m=mt.o.stringify;for(g in d)if(Object.prototype.hasOwnProperty.call(d,g))switch(q=
d[g],typeof q){case "undefined":case "unknown":case "function":break;default:e&&f.push(","),e=1,f.push(m(g)+":"+m(q))}f.push("}");return f.join("")}}}();mt.localStorage={};mt.localStorage.ua=function(){if(!mt.localStorage.l)try{mt.localStorage.l=document.createElement("input"),mt.localStorage.l.type="hidden",mt.localStorage.l.style.display="none",mt.localStorage.l.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.l)}catch(a){return x}return v};
mt.localStorage.set=function(a,b,g){var d=new Date;d.setTime(d.getTime()+g||31536E6);try{window.localStorage?(b=d.getTime()+"|"+b,window.localStorage.setItem(a,b)):mt.localStorage.ua()&&(mt.localStorage.l.expires=d.toUTCString(),mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.setAttribute(a,b),mt.localStorage.l.save(document.location.hostname))}catch(e){}};
mt.localStorage.get=function(a){if(window.localStorage){if(a=window.localStorage.getItem(a)){var b=a.indexOf("|"),g=a.substring(0,b)-0;if(g&&g>(new Date).getTime())return a.substring(b+1)}}else if(mt.localStorage.ua())try{return mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.getAttribute(a)}catch(d){}return w};
mt.localStorage.remove=function(a){if(window.localStorage)window.localStorage.removeItem(a);else if(mt.localStorage.ua())try{mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.removeAttribute(a),mt.localStorage.l.save(document.location.hostname)}catch(b){}};mt.sessionStorage={};mt.sessionStorage.set=function(a,b){try{window.sessionStorage&&window.sessionStorage.setItem(a,b)}catch(g){}};
mt.sessionStorage.get=function(a){try{return window.sessionStorage?window.sessionStorage.getItem(a):w}catch(b){return w}};mt.sessionStorage.remove=function(a){try{window.sessionStorage&&window.sessionStorage.removeItem(a)}catch(b){}};mt.jb={};mt.jb.log=function(a,b){var g=new Image,d="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[d]=g;g.onload=function(){g.onload=w;g=window[d]=w;b&&b(a)};g.src=a};mt.Ja={};
mt.Ja.Xb=function(){var a="";if(navigator.plugins&&navigator.mimeTypes.length){var b=navigator.plugins["Shockwave Flash"];b&&b.description&&(a=b.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(a=b.GetVariable("$version"))&&(a=a.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(g){}return a};
mt.Ja.Fc=function(a,b,g,d,e){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+a+'" width="'+g+'" height="'+d+'"><param name="movie" value="'+b+'" /><param name="flashvars" value="'+(e||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+a+'" width="'+g+'" height="'+d+'" src="'+b+'" flashvars="'+(e||"")+'" allowscriptaccess="always" /></object>'};
h.z={Hc:"http://tongji.baidu.com/hm-web/welcome/ico",Ia:"hm.baidu.com/hm.gif",vb:/^(tongji|hmcdn).baidu.com$/,nb:"tongji.baidu.com",bc:"hmmd",dc:"hmpl",Bc:"utm_medium",ac:"hmkw",Dc:"utm_term",Zb:"hmci",Ac:"utm_content",ec:"hmsr",Cc:"utm_source",$b:"hmcu",zc:"utm_campaign",M:0,I:Math.round(+new Date/1E3),protocol:"https:"===document.location.protocol?"https:":"http:",la:"https:",Ic:0,Bb:6E5,Jc:6E5,rc:5E3,Cb:5,O:1024,Ab:1,Z:2147483647,mb:"hca kb cc cf ci ck cl cm cp cu cw ds vl ep et fl ja ln lo lt rnd si su v cv lv api sn p ct u tt".split(" "),
V:v,Oa:["a","input","button"],La:{id:"data-hm-id",ba:"data-hm-class",aa:"data-hm-xpath",content:"data-hm-content",qa:"data-hm-tag",link:"data-hm-link"},Na:"data-hm-enabled",Ma:"data-hm-disabled",nc:"https://hmcdn.baidu.com/static/tongji/plugins/",cb:["UrlChangeTracker"]};(function(){var a={D:{},e:function(a,g){this.D[a]=this.D[a]||[];this.D[a].push(g)},J:function(a,g){this.D[a]=this.D[a]||[];for(var d=this.D[a].length,e=0;e<d;e++)this.D[a][e](g)}};return h.w=a})();
(function(){function a(a,d){var e=document.createElement("script");e.charset="utf-8";b.d(d,"Function")&&(e.readyState?e.onreadystatechange=function(){if("loaded"===e.readyState||"complete"===e.readyState)e.onreadystatechange=w,d()}:e.onload=function(){d()});e.src=a;var l=document.getElementsByTagName("script")[0];l.parentNode.insertBefore(e,l)}var b=mt.lang;return h.load=a})();
(function(){var a=mt.cookie,b=mt.localStorage,g=mt.sessionStorage,d={getData:function(d){try{return a.get(d)||g.get(d)||b.get(d)}catch(l){}},setData:function(e,l,f){try{a.set(e,l,{domain:d.R(),path:d.da(),Q:f}),f?b.set(e,l,f):g.set(e,l)}catch(m){}},removeData:function(e){try{a.set(e,"",{domain:d.R(),path:d.da(),Q:-1}),g.remove(e),b.remove(e)}catch(l){}},W:function(a,d){a="."+a.replace(/:\d+/,"");d="."+d.replace(/:\d+/,"");var b=a.indexOf(d);return-1<b&&b+d.length===a.length},ka:function(a,d){a=a.replace(/^https?:\/\//,
"");return 0===a.indexOf(d)},R:function(){for(var a=document.location.hostname,b=0,f=c.dm.length;b<f;b++)if(d.W(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[/?#].*/,"");return a},da:function(){for(var a=0,b=c.dm.length;a<b;a++){var f=c.dm[a];if(-1<f.indexOf("/")&&d.ka(document.location.href,f))return f.replace(/^[^/]+(\/.*)/,"$1")+"/"}return"/"}};return h.xa=d})();
(function(){var a=mt.lang,b=mt.o,g=h.xa,d={pageview:{},session:{},autoEventTracking:{},customEvent:{},user:{}},e={user:1,session:2,pageview:3,autoEventTracking:3,customEvent:3,others:3},l=["session","user"],f="Hm_up_"+c.id,m={init:function(){m.hc()},hc:function(){try{var e=b.parse(decodeURIComponent(g.getData(f)));a.d(e,"Object")&&(d.user=e)}catch(t){}},A:function(a){var b={};d[a]!==s&&(b=d[a]);a=this.Da();for(var e in b)b.hasOwnProperty(e)&&(a[e]=b[e]);return a},Da:function(){for(var a={},b,e=l.length-
1;0<=e;e--){b=d[l[e]];for(var n in b)b.hasOwnProperty(n)&&(a[n]=b[n])}return a},setProperty:function(e,f,g){var n=d[e];if(a.d(n,"Object")&&a.d(f,"Object")){for(var u in f)if(f.hasOwnProperty(u)){var k=a.h(String(u));if(g||!/^_/.test(k)&&!/_$/.test(k)||/^(_iden|ei_|ec_|ex_|en_|et_|el_)$/.test(k)){var p=f[u];if(p==w)delete n[k];else{if(a.d(p,"Object")||a.d(p,"Array"))p=b.stringify(p);p=a.h(String(p));m.kc(e,k,p)&&(n[k]={value:p,scope:m.Va(e)})}}}"user"===e&&m.Ga()}},r:function(b){b!==s&&("userId"===
b&&a.d(d.user,"Object")?(delete d.user.uid_,m.Ga()):"user"===b&&a.d(d.user,"Object")?(b=d.user.uid_,d.user=b===s?{}:{uid_:b},m.Ga()):d[b]!==s&&(d[b]={}))},Ga:function(){try{g.setData(f,encodeURIComponent(b.stringify(d.user)),c.age)}catch(a){}},kc:function(a,b,e){var n=v,f=d[a];if(256<encodeURIComponent(String(b)).length||256<encodeURIComponent(String(e)).length)n=x;else{var k=f[b];f[b]={value:e,scope:m.Va(a)};a=m.N(m.A(a));2048<encodeURIComponent(a).length&&(k!==s?f[b]=k:delete f[b],n=x)}return n},
N:function(a){var d=[],b,e;for(e in a)a.hasOwnProperty(e)&&(b=[e,a[e].value],(1===a[e].scope||2===a[e].scope)&&b.push(a[e].scope),d.push(b.join("*")));return d.join("!")},Va:function(a){a=e[a];return a!==s?a:e.others}};return h.P=m})();
(function(){var a=mt.f,b=mt.lang,g=mt.o,d=h.w,e=h.P,l=e.N;if(b.isArray(c.cptrk)&&0<c.cptrk.length){var f={bb:{},ra:{},init:function(){for(var a,d=0;d<c.cptrk.length;d++)try{if(a=g.parse(decodeURIComponent(String(c.cptrk[d]))),a.a!==s&&b.d(a.a,"Object")){var e=a.a,r;for(r in e)e.hasOwnProperty(r)&&(f.ra[r]=String(e[r]))}}catch(n){}},ab:function(){var d,b,e;for(e in f.ra)if(f.ra.hasOwnProperty(e)&&f.bb[e]===s&&(d=f.ra[e],d=a.Aa(d)))b=b===s?{}:b,b[e]=a.S(d,x),f.bb[e]=v;return b},Ea:function(){var a=
f.ab();a&&f.tc(a)},gc:function(){"MutationObserver"in window?(new MutationObserver(f.Ea)).observe(document.body,{childList:v,subtree:v}):window.setInterval(f.Ea,15E3)},tc:function(a){if(b.d(a,"Object")){e.setProperty("pageview",a);a=h.c.b.p;var d=h.c.b.ep;h.c.b.et=9;h.c.b.ep="";h.c.b.p=l(e.A("pageview"));h.c.i();h.c.b.p=a;h.c.b.ep=d;e.r("pageview")}}};f.init();d.e("pv-b",function(){var a=f.ab();a&&e.setProperty("pageview",a)});f.gc();a.eb(f.Ea)}})();
(function(){var a=mt.lang,b=mt.f,g={ca:function(a,e){return function(l){var f=l.target||l.srcElement;if(f){var m=f.getAttribute(a.ta);l=l.clientX+":"+l.clientY;if(m&&m===l)f.removeAttribute(a.ta);else if(e&&0<e.length&&(f=b.Tb(f))&&f.length)if(m=f.length,l=f[f.length-1],1E4>m*l.split(">").length)for(l=0;l<m;l++)g.ib(a,f[l]);else g.ib(a,l)}}},ib:function(d,b){for(var g={},f=String(b).split(">").length,m=0;m<f;m++)g[b]="",b=b.substring(0,b.lastIndexOf(">"));d&&(a.d(d,"Object")&&d.Pa)&&d.Pa(g)},pc:function(a,
b){return function(g){(g.target||g.srcElement).setAttribute(a.ta,g.clientX+":"+g.clientY);a&&a.s&&(b?a.s(b):a.s("#"+encodeURIComponent(this.id),g.type))}}};return h.za=g})();
(function(){var a=mt.f,b=mt.o,g=mt.event,d=mt.lang,e=h.z,l=h.za,f=h.P,m=f.N,q={ta:"HM_ce",pb:function(){if(c.cetrk&&c.cetrk.length){g.e(document,"click",l.ca(q,c.cetrk));for(var d=0,e=c.cetrk.length;d<e;d++){var n;try{n=b.parse(decodeURIComponent(String(c.cetrk[d])))}catch(f){n={}}var k=n.p||"";-1===k.indexOf(">")&&(0===k.indexOf("#")&&(k=k.substring(1)),(k=a.Ra(k))&&g.e(k,"click",l.pc(q,n)))}}},Pa:function(a){if(c.cetrk&&c.cetrk.length)for(var d=0,e=c.cetrk.length;d<e;d++){var f;try{f=b.parse(decodeURIComponent(String(c.cetrk[d])))}catch(k){f=
{}}var p=q.Nb(f.p,a);p&&q.s(f,p)}},Nb:function(a,b){a=String(a);if(0<a.indexOf("*")){var d=RegExp("^"+a.replace(/\[/g,"\\[").replace(/\]/g,"\\]").replace(/\*/,"\\d+")+"$"),e;for(e in b)if(b.hasOwnProperty(e)&&d.test(e))return e;return w}return b.hasOwnProperty(a)?a:w},s:function(b,e){h.c.b.et=7;var n=b&&b.k||"",n=d.h(n),g={};if(b&&b.a&&d.d(b.a,"Object")){var k=b.a,p;for(p in k)if(k.hasOwnProperty(p)){var y=q.Ub(k[p]||"",e),y=y?a.S(y,x):"";g[p]=y}}g=q.Jb(g,e||b&&b.p);g._iden=n;f.setProperty("customEvent",
g);h.c.b.ep="";h.c.b.p=m(f.A("customEvent"));h.c.i();h.c.b.p="";f.r("customEvent")},Jb:function(b,d){var f=a.Aa(d),g=e.La;f&&(c.aet&&c.aet.length?(b.ei_=a.getAttribute(f,g.id)||a.getAttribute(f,"id")||"",b.ec_=a.getAttribute(f,g.ba)||a.getAttribute(f,"class")||"",b.ex_=a.getAttribute(f,g.aa)||a.ea(f),b.en_=a.getAttribute(f,g.content)||a.S(f,v),b.et_=a.getAttribute(f,g.qa)||a.T(f),b.el_=a.getAttribute(f,g.link)||a.getAttribute(f,"href")||""):(b.ex_=a.getAttribute(f,g.aa)||a.ea(f),b.en_=a.getAttribute(f,
g.content)||a.S(f,v)));return b},Ub:function(b,d){b=String(b);d=String(d);if(0<b.indexOf("*")){var e=/.*\[(\d+)\]$/.exec(d);b=b.replace("*",e?e[1]:"1")}return a.Aa(b)}};h.w.e("pv-b",q.pb);return q})();
(function(){var a=mt.f,b=mt.lang,g=mt.event,d=mt.g,e=h.z,l=[],f={ob:function(){c.ctrk&&(g.e(document,"mouseup",f.zb()),g.e(window,"unload",function(){f.oa()}),setInterval(function(){f.oa()},e.Bb))},zb:function(){return function(a){a=f.Kb(a);if(""!==a){var b=(e.la+"//"+e.Ia+"?"+h.c.hb().replace(/ep=[^&]*/,"ep="+encodeURIComponent(a))).length;b+(e.Z+"").length>e.O||(b+encodeURIComponent(l.join("!")+(l.length?"!":"")).length+(e.Z+"").length>e.O&&f.oa(),l.push(a),(l.length>=e.Cb||/\*a\*/.test(a))&&f.oa())}}},
Kb:function(g){var q=g.target||g.srcElement;if(0===e.Ab){var l=(q.tagName||"").toLowerCase();if("embed"==l||"object"==l)return""}var r;d.ga?(r=Math.max(document.documentElement.scrollTop,document.body.scrollTop),l=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),l=g.clientX+l,r=g.clientY+r):(l=g.pageX,r=g.pageY);g=f.Rb(g,q,l,r);var n=window.innerWidth||document.documentElement.clientWidth||document.body.offsetWidth;switch(c.align){case 1:l-=n/2;break;case 2:l-=n}n=[];n.push(l);
n.push(r);n.push(g.ma);n.push(g.na);n.push(g.oc);n.push(b.h(g.mc));n.push(g.sa);n.push(g.fa);(q="a"===(q.tagName||"").toLowerCase()?q:a.Sa(q))?(n.push("a"),n.push(b.h(encodeURIComponent(q.href)))):n.push("b");return n.join("*")},Rb:function(e,f,g,l){e=a.ea(f);var n=0,u=0,k=0,p=0;if(f&&(n=f.offsetWidth||f.clientWidth,u=f.offsetHeight||f.clientHeight,p=a.Ta(f),k=p.left,p=p.top,b.d(f.getBBox,"Function")&&(u=f.getBBox(),n=u.width,u=u.height),"html"===(f.tagName||"").toLowerCase()))n=Math.max(n,f.clientWidth),
u=Math.max(u,f.clientHeight);return{ma:Math.round(100*((g-k)/n)),na:Math.round(100*((l-p)/u)),oc:d.orientation,mc:e,sa:n,fa:u}},oa:function(){0!==l.length&&(h.c.b.et=2,h.c.b.ep=l.join("!"),h.c.i(),l=[])}};h.w.e("pv-b",f.ob);return f})();
(function(){var a=mt.lang,b=mt.f,g=mt.event,d=mt.g,e=h.z,l=h.w,f=h.P,m=f.N,q=+new Date,t=[],r={ca:function(){return function(d){if(h.c&&h.c.V&&c.aet&&c.aet.length){var f=d.target||d.srcElement;if(f){var g=h.c.Oa,p=b.getAttribute(f,e.Na)!=w?v:x;if(b.getAttribute(f,e.Ma)==w)if(p)r.va(r.Ba(f,d));else{var y=b.T(f);if(a.F(g,"*")||a.F(g,y))r.va(r.Ba(f,d));else for(;f.parentNode!=w;){var p=f.parentNode,y=b.T(p),z="a"===y&&a.F(g,"a")?v:x,y="button"===y&&a.F(g,"button")?v:x,A=b.getAttribute(p,e.Na)!=w?v:x;
if(b.getAttribute(p,e.Ma)==w&&(z||y||A)){r.va(r.Ba(p,d));break}f=f.parentNode}}}}}},Ba:function(f,g){var k={},p=e.La;k.id=b.getAttribute(f,p.id)||b.getAttribute(f,"id")||"";k.ba=b.getAttribute(f,p.ba)||b.getAttribute(f,"class")||"";k.aa=b.getAttribute(f,p.aa)||b.ea(f);k.content=b.getAttribute(f,p.content)||b.S(f,v);k.qa=b.getAttribute(f,p.qa)||b.T(f);k.link=b.getAttribute(f,p.link)||b.getAttribute(f,"href")||"";k.type=g.type||"click";p=a.Ya(f.offsetTop)?f.offsetTop:0;"click"===g.type?p=d.ga?g.clientY+
Math.max(document.documentElement.scrollTop,document.body.scrollTop):g.pageY:"touchend"===g.type&&(g.$a&&g.$a.changedTouches)&&(p=g.$a.changedTouches[0].pageY);k.yc=p;p=this.Mb(g);k.ma=p.ma||0;k.na=p.na||0;k.sa=p.sa||0;k.fa=p.fa||0;k.lb=p.lb||"b";return k},Mb:function(f){var e=f.target||f.srcElement,g;if(d.ga){var p=Math.max(document.documentElement.scrollTop,document.body.scrollTop);g=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft);g=f.clientX+g;f=f.clientY+p}else g=f.pageX,
f=f.pageY;var y=p=0,z=0,A=0;if(e&&(p=e.offsetWidth||e.clientWidth,y=e.offsetHeight||e.clientHeight,A=b.Ta(e),z=A.left,A=A.top,a.d(e.getBBox,"Function")&&(y=e.getBBox(),p=y.width,y=y.height),"html"===(e.tagName||"").toLowerCase()))p=Math.max(p,e.clientWidth),y=Math.max(y,e.clientHeight);return{ma:Math.round(100*((g-z)/p)),na:Math.round(100*((f-A)/y)),sa:p,fa:y,lb:("a"===(e.tagName||"").toLowerCase()?e:b.Sa(e))?"a":"b"}},va:function(b){var d=a.h;b=[+new Date-(h.c.X!==s?h.c.X:q),d(b.id),d(b.ba),d(b.qa),
d(b.aa),d(b.link),d(b.content),b.type,b.yc].join("*");r.wa(b);a.d(this.$(),"Function")&&this.$()()},wa:function(a){a.length>e.O||(encodeURIComponent(t.join("!")+a).length>e.O&&(r.s(t.join("!")),t=[]),t.push(a))},s:function(a){h.c.b.et=5;h.c.b.ep=a;h.c.b.p=m(f.A("autoEventTracking"));h.c.i();h.c.b.p=""},$:function(){return function(){t&&t.length&&(r.s(t.join("!")),t=[])}}};a.G(c.aet)&&""!==c.aet&&l.e("pv-b",function(){g.e(document,"click",r.ca());"ontouchend"in document&&g.e(window,"touchend",r.ca());
g.e(window,"unload",r.$())});return r})();
(function(){var a=mt.lang,b=mt.event,g=mt.g,d=h.z,e=h.w,l=+new Date,f=[],m=w,q={tb:function(){a.G(c.aet)&&""!==c.aet&&setInterval(q.gb,d.rc)},gb:function(){var a=g.U()+g.L();0<a-h.c.b.vl&&(h.c.b.vl=a)}},t={Fb:function(){return function(){h.c&&(h.c.V&&c.aet&&c.aet.length)&&(window.clearTimeout(m),m=window.setTimeout(function(){t.rb(g.U()+g.L())},150))}},rb:function(a){t.wa([+new Date-(h.c.X!==s?h.c.X:l),a].join("*"))},wa:function(a){if(encodeURIComponent(f.join("!")+a).length>d.O||3<f.length)t.s(f.join("!")),
f=[];f.push(a)},s:function(a){q.gb();h.c.b.et=6;h.c.b.vh=g.L();h.c.b.ep=a;h.c.i()},$:function(){return function(){f&&f.length&&(t.s(f.join("!")),f=[])}}};a.G(c.aet)&&""!==c.aet&&e.e("pv-b",function(){b.e(window,"scroll",t.Fb());b.e(window,"unload",t.$());q.tb()});return t})();
(function(){function a(){return function(){h.c.b.nv=0;h.c.b.st=4;h.c.b.et=3;h.c.b.ep=h.ya.Sb()+","+h.ya.Ob();h.c.i()}}function b(){clearTimeout(z);var a;p&&(a="visible"==document[p]);y&&(a=!document[y]);m="undefined"==typeof a?v:a;if((!f||!q)&&m&&t)k=v,n=+new Date;else if(f&&q&&(!m||!t))k=x,u+=+new Date-n;f=m;q=t;z=setTimeout(b,100)}function g(a){var p=document,b="";if(a in p)b=a;else for(var d=["webkit","ms","moz","o"],f=0;f<d.length;f++){var e=d[f]+a.charAt(0).toUpperCase()+a.slice(1);if(e in p){b=
e;break}}return b}function d(a){if(!("focus"==a.type||"blur"==a.type)||!(a.target&&a.target!=window))t="focus"==a.type||"focusin"==a.type?v:x,b()}var e=mt.event,l=h.w,f=v,m=v,q=v,t=v,r=+new Date,n=r,u=0,k=v,p=g("visibilityState"),y=g("hidden"),z;b();(function(){var a=p.replace(/[vV]isibilityState/,"visibilitychange");e.e(document,a,b);e.e(window,"pageshow",b);e.e(window,"pagehide",b);"object"==typeof document.onfocusin?(e.e(document,"focusin",d),e.e(document,"focusout",d)):(e.e(window,"focus",d),
e.e(window,"blur",d))})();h.ya={Sb:function(){return+new Date-r},Ob:function(){return k?+new Date-n+u:u}};l.e("pv-b",function(){e.e(window,"unload",a())});l.e("duration-send",a());l.e("duration-done",function(){n=r=+new Date;u=0});return h.ya})();
(function(){var a=mt.lang,b=h.z,g=h.load,d={fc:function(d){if((window._dxt===s||a.d(window._dxt,"Array"))&&"undefined"!==typeof h.c){var l=h.c.R();g([b.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(l)].join(""),d)}},xc:function(b){if(a.d(b,"String")||a.d(b,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",b])}};return h.Db=d})();
(function(){function a(a,b,d,f){if(!(a===s||b===s||f===s)){if(""===a)return[b,d,f].join("*");a=String(a).split("!");for(var e,g=x,k=0;k<a.length;k++)if(e=a[k].split("*"),String(b)===e[0]){e[1]=d;e[2]=f;a[k]=e.join("*");g=v;break}g||a.push([b,d,f].join("*"));return a.join("!")}}function b(a){for(var f in a)if({}.hasOwnProperty.call(a,f)){var e=a[f];d.d(e,"Object")||d.d(e,"Array")?b(e):a[f]=String(e)}}var g=mt.url,d=mt.lang,e=mt.o,l=mt.g,f=h.z,m=h.w,q=h.Db,t=h.load,r=h.xa,n=h.P,u=n.N,k={Y:[],pa:0,Za:x,
C:{Ka:"",page:""},init:function(){k.j=0;n.init();m.e("pv-b",function(){k.Eb();k.Gb()});m.e("pv-d",function(){k.Hb();k.C.page=""});m.e("stag-b",function(){h.c.b.api=k.j||k.pa?k.j+"_"+k.pa:"";h.c.b.ct=[decodeURIComponent(r.getData("Hm_ct_"+c.id)||""),k.C.Ka,k.C.page].join("!")});m.e("stag-d",function(){h.c.b.api=0;k.j=0;k.pa=0})},Eb:function(){var a=window._hmt||[];if(!a||d.d(a,"Array"))window._hmt={id:c.id,cmd:{},push:function(){for(var a=window._hmt,b=0;b<arguments.length;b++){var p=arguments[b];
d.d(p,"Array")&&(a.cmd[a.id].push(p),"_setAccount"===p[0]&&(1<p.length&&/^[0-9a-f]{32}$/.test(p[1]))&&(p=p[1],a.id=p,a.cmd[p]=a.cmd[p]||[]))}}},window._hmt.cmd[c.id]=[],window._hmt.push.apply(window._hmt,a)},Gb:function(){var a=window._hmt;if(a&&a.cmd&&a.cmd[c.id])for(var b=a.cmd[c.id],d=/^_track(Event|MobConv|Order)$/,f=0,e=b.length;f<e;f++){var g=b[f];d.test(g[0])?k.Y.push(g):k.Ha(g)}a.cmd[c.id]={push:k.Ha}},Hb:function(){if(0<k.Y.length)for(var a=0,b=k.Y.length;a<b;a++)k.Ha(k.Y[a]);k.Y=w},Ha:function(a){var b=
a[0];if(k.hasOwnProperty(b)&&d.d(k[b],"Function"))k[b](a)},_setAccount:function(a){1<a.length&&/^[0-9a-f]{32}$/.test(a[1])&&(k.j|=1)},_setAutoPageview:function(a){if(1<a.length&&(a=a[1],x===a||v===a))k.j|=2,h.c.Wa=a},_trackPageview:function(a){if(1<a.length&&a[1].charAt&&"/"===a[1].charAt(0)){k.j|=4;h.c.b.sn=h.c.Ua();h.c.b.et=0;h.c.b.ep="";h.c.b.vl=l.U()+l.L();h.c.b.kb=0;h.c.Fa?(h.c.b.nv=0,h.c.b.st=4):h.c.Fa=v;var b=h.c.b.u,d=h.c.b.su;h.c.b.u=f.protocol+"//"+document.location.host+a[1];k.Za||(h.c.b.su=
document.location.href);h.c.b.p=u(n.A("pageview"));h.c.i();h.c.b.u=b;h.c.b.su=d;h.c.b.p="";h.c.X=+new Date;n.r("pageview")}},_trackEvent:function(a){2<a.length&&(k.j|=8,h.c.b.nv=0,h.c.b.st=4,h.c.b.et=4,h.c.b.ep=d.h(a[1])+"*"+d.h(a[2])+(a[3]?"*"+d.h(a[3]):"")+(a[4]?"*"+d.h(a[4]):""),h.c.b.p=u(n.Da()),h.c.i(),h.c.b.p="")},_setCustomVar:function(a){if(!(4>a.length)){var b=a[1],f=a[4]||3;if(0<b&&6>b&&0<f&&4>f){k.pa++;for(var e=(h.c.b.cv||"*").split("!"),g=e.length;g<b-1;g++)e.push("*");e[b-1]=f+"*"+d.h(a[2])+
"*"+d.h(a[3]);h.c.b.cv=e.join("!");a=h.c.b.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,"");""!==a?r.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):r.removeData("Hm_cv_"+c.id)}}},_setUserTag:function(b){if(!(3>b.length)){var f=d.h(b[1]);b=d.h(b[2]);if(f!==s&&b!==s){var e=decodeURIComponent(r.getData("Hm_ct_"+c.id)||""),e=a(e,f,1,b);r.setData("Hm_ct_"+c.id,encodeURIComponent(e),c.age)}}},_setVisitTag:function(b){if(!(3>b.length)){var f=d.h(b[1]);b=d.h(b[2]);if(f!==s&&b!==s){var e=
k.C.Ka,e=a(e,f,2,b);k.C.Ka=e}}},_setPageTag:function(b){if(!(3>b.length)){var f=d.h(b[1]);b=d.h(b[2]);if(f!==s&&b!==s){var e=k.C.page,e=a(e,f,3,b);k.C.page=e}}},_setReferrerOverride:function(a){1<a.length&&(h.c.b.su=a[1].charAt&&"/"===a[1].charAt(0)?f.protocol+"//"+window.location.host+a[1]:a[1],k.Za=v)},_trackOrder:function(a){a=a[1];d.d(a,"Object")&&(b(a),k.j|=16,h.c.b.nv=0,h.c.b.st=4,h.c.b.et=94,h.c.b.ep=e.stringify(a),h.c.b.p=u(n.Da()),h.c.i(),h.c.b.p="")},_trackMobConv:function(a){if(a={webim:1,
tel:2,map:3,sms:4,callback:5,share:6}[a[1]])k.j|=32,h.c.b.et=93,h.c.b.ep=a,h.c.i()},_setDataxId:function(a){a=a[1];q.fc();q.xc(a)},_setUserId:function(a){a=a[1];if(a!==s&&(d.G(a)||d.Ya(a))){var b=n.A("user").uid_;if(!(b&&b.value===d.h(String(a)))){var b=h.c.b.p,f=h.c.b.ep;h.c.b.et=8;h.c.b.ep="";h.c.b.p="uid_*"+d.h(String(a));h.c.i();var e={};e.uid_=a;n.setProperty("user",e,v);h.c.b.p=b;h.c.b.ep=f}}},_clearUserId:function(a){1<a.length&&v===a[1]&&n.r("userId")},_setUserProperty:function(a){a=a[1];
d.d(a,"Object")&&n.setProperty("user",a)},_clearUserProperty:function(a){1<a.length&&v===a[1]&&n.r("user")},_setSessionProperty:function(a){a=a[1];d.d(a,"Object")&&n.setProperty("session",a)},_clearSessionProperty:function(a){1<a.length&&v===a[1]&&n.r("session")},_setPageviewProperty:function(a){a=a[1];d.d(a,"Object")&&n.setProperty("pageview",a)},_clearPageviewProperty:function(a){1<a.length&&v===a[1]&&n.r("pageview")},_setAutoEventTrackingProperty:function(a){a=a[1];d.d(a,"Object")&&n.setProperty("autoEventTracking",
a)},_clearAutoEventTrackingProperty:function(a){1<a.length&&v===a[1]&&n.r("autoEventTracking")},_setAutoTracking:function(a){if(1<a.length&&(a=a[1],x===a||v===a))h.c.Xa=a},_setAutoEventTracking:function(a){if(1<a.length&&(a=a[1],x===a||v===a))h.c.V=a},_trackPageDuration:function(a){1<a.length?(a=a[1],2===String(a).split(",").length&&(h.c.b.et=3,h.c.b.ep=a,h.c.i())):m.J("duration-send");m.J("duration-done")},_require:function(a){1<a.length&&(a=a[1],f.vb.test(g.K(a))&&t(a))},_providePlugin:function(a){if(1<
a.length){var b=window._hmt,e=a[1];a=a[2];if(d.F(f.cb,e)&&d.d(a,"Function")&&(b.plugins=b.plugins||{},b.H=b.H||{},b.plugins[e]=a,b.B=b.B||[],a=b.B.slice(),e&&a.length&&a[0][1]===e))for(var g=0,k=a.length;g<k;g++){var l=a[g][2]||{};if(b.plugins[e]&&!b.H[e])b.H[e]=new b.plugins[e](l),b.B.shift();else break}}},_requirePlugin:function(a){if(1<a.length){var b=window._hmt,e=a[1],g=a[2]||{};if(d.F(f.cb,e))if(b.plugins=b.plugins||{},b.H=b.H||{},b.plugins[e]&&!b.H[e])b.H[e]=new b.plugins[e](g);else{b.B=b.B||
[];for(var g=0,l=b.B.length;g<l;g++)if(b.B[g][1]===e)return;b.B.push(a);k._require([w,f.nc+e+".js"])}}},_trackCustomEvent:function(a){if(1<a.length){var b=a[1];a=a[2];d.d(a,"Object")||(a={});a._iden=b;n.setProperty("customEvent",a);h.c.b.et=7;h.c.b.ep="";h.c.b.p=u(n.A("customEvent"));h.c.i();h.c.b.p="";n.r("customEvent")}}};k.init();h.wb=k;return h.wb})();
(function(){var a=h.w;c.spa!==s&&"1"===String(c.spa)&&(window._hmt=window._hmt||[],window._hmt.push(["_requirePlugin","UrlChangeTracker"]),a.e("pv-b",function(){""!==window.location.hash&&(h.c.b.u=window.location.href)}))})();
(function(){function a(){"undefined"===typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=v,this.b={},this.Xa=this.Wa=v,this.V=k.V,this.Oa=e.G(c.aet)&&0<c.aet.length?c.aet.split(","):"",this.Fa=x,this.init())}var b=mt.url,g=mt.jb,d=mt.Ja,e=mt.lang,l=mt.cookie,f=mt.g,m=mt.sessionStorage,q=mt.o,t=mt.event,r=h.xa,n=h.P,u=n.N,k=h.z,p=h.load,y=h.w;a.prototype={W:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length===a.length},ka:function(a,
b){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(b)},ha:function(a){for(var d=0;d<c.dm.length;d++)if(-1<c.dm[d].indexOf("/")){if(this.ka(a,c.dm[d]))return v}else{var e=b.K(a);if(e&&this.W(e,c.dm[d]))return v}return x},R:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(this.W(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[/?#].*/,"");return a},da:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&this.ka(document.location.href,d))return d.replace(/^[^/]+(\/.*)/,
"$1")+"/"}return"/"},Vb:function(){if(!document.referrer)return k.I-k.M>c.vdur?1:4;var a=x;this.ha(document.referrer)&&this.ha(document.location.href)?a=v:(a=b.K(document.referrer),a=this.W(a||"",document.location.hostname));return a?k.I-k.M>c.vdur?1:4:3},vc:function(){var a,b,d,e,f,g;k.M=r.getData("Hm_lpvt_"+c.id)||0;13===k.M.length&&(k.M=Math.round(k.M/1E3));b=this.Vb();a=4!==b?1:0;if(g=r.getData("Hm_lvt_"+c.id)){e=g.split(",");for(f=e.length-1;0<=f;f--)13===e[f].length&&(e[f]=""+Math.round(e[f]/
1E3));for(;2592E3<k.I-e[0];)e.shift();f=4>e.length?2:3;for(1===a&&e.push(k.I);4<e.length;)e.shift();g=e.join(",");e=e[e.length-1]}else g=k.I,e="",f=1;this.ic()?(r.setData("Hm_lvt_"+c.id,g,c.age),r.setData("Hm_lpvt_"+c.id,k.I),d=l.lc(this.R(),this.da())):this.Ib();if(0===c.nv&&this.ha(document.location.href)&&(""===document.referrer||this.ha(document.referrer)))a=0,b=4;this.b.nv=a;this.b.st=b;this.b.cc=d;this.b.lt=e;this.b.lv=f},ic:function(){var a=b.K(document.location.href);return!e.F("sjh.baidu.com isite.baidu.com ls.wejianzhan.com bs.wejianzhan.com product.weijianzhan.com qianhu.weijianzhan.com aisite.wejianzhan.com".split(" "),
a)},Ib:function(){for(var a=document.cookie.split(";"),b=0;b<a.length;b++){var d=a[b].split("=");d.length&&/Hm_(up|ct|cv|lp?vt)_[0-9a-f]{31}/.test(String(d[0]))&&r.removeData(d[0]);d.length&&/Hm_ck_[0-9]{13}/.test(String(d[0]))&&r.removeData(d[0])}},hb:function(){for(var a=[],b=this.b.et,d=0,e=k.mb.length;d<e;d++){var f=k.mb[d],g=this.b[f];"undefined"!==typeof g&&""!==g&&("tt"!==f||"tt"===f&&0===b)&&("ct"!==f||"ct"===f&&0===b)&&a.push(f+"="+encodeURIComponent(g))}return a.join("&")},wc:function(){this.vc();
this.b.si=c.id;this.b.sn=this.Ua();this.b.su=document.referrer;this.b.ds=f.qc;this.b.cl=f.colorDepth+"-bit";this.b.ln=String(f.language).toLowerCase();this.b.ja=f.javaEnabled?1:0;this.b.ck=f.cookieEnabled?1:0;this.b.lo="number"===typeof _bdhm_top?1:0;this.b.fl=d.Xb();this.b.v="1.2.72";this.b.cv=decodeURIComponent(r.getData("Hm_cv_"+c.id)||"");this.b.tt=document.title||"";this.b.vl=f.U()+f.L();var a=document.location.href;this.b.cm=b.m(a,k.bc)||"";this.b.cp=b.m(a,k.dc)||b.m(a,k.Bc)||"";this.b.cw=b.m(a,
k.ac)||b.m(a,k.Dc)||"";this.b.ci=b.m(a,k.Zb)||b.m(a,k.Ac)||"";this.b.cf=b.m(a,k.ec)||b.m(a,k.Cc)||"";this.b.cu=b.m(a,k.$b)||b.m(a,k.zc)||"";f.jc()&&(this.b.u=window.location.href)},init:function(){try{this.wc(),0===this.b.nv?this.uc():this.Qa(),h.c=this,this.yb(),this.xb(),y.J("pv-b"),this.sc()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));g.log(k.la+"//"+k.Ia+"?"+b.join("&"))}},
sc:function(){function a(){y.J("pv-d")}this.Wa?(this.Fa=v,this.b.et=0,this.b.ep="",this.b.p=u(n.A("pageview")),this.b.vl=f.U()+f.L(),this.i(a),this.b.p=""):a();this.X=+new Date;n.r("pageview")},i:function(a){if(this.Xa){var b=this;b.b.rnd=Math.round(Math.random()*k.Z);y.J("stag-b");var d=k.la+"//"+k.Ia+"?"+b.hb();y.J("stag-d");b.ub(d);g.log(d,function(d){b.fb(d);e.d(a,"Function")&&a.call(b)})}},yb:function(){var a=document.location.hash.substring(1),d=RegExp(c.id),e=b.K(document.referrer)===k.nb?
1:0,f=b.m(a,"jn"),g=/^heatlink$|^select$|^pageclick$/.test(f);a&&(d.test(a)&&e&&g)&&(this.b.rnd=Math.round(Math.random()*k.Z),a=document.createElement("script"),a.setAttribute("type","text/javascript"),a.setAttribute("charset","utf-8"),a.setAttribute("src",k.protocol+"//"+c.js+f+".js?"+this.b.rnd),f=document.getElementsByTagName("script")[0],f.parentNode.insertBefore(a,f))},xb:function(){if(window.postMessage&&window.self!==window.parent){var a=this;t.e(window,"message",function(d){if(b.K(d.origin)===
k.nb){d=d.data||{};var e=d.jn||"",f=/^customevent$|^heatmap$/.test(e);if(RegExp(c.id).test(d.sd||"")&&f)a.b.rnd=Math.round(Math.random()*k.Z),p(k.protocol+"//"+c.js+e+".js?"+a.b.rnd)}});window.parent.postMessage({id:c.id,url:document.location.href,status:"__Messenger__hmLoaded"},"*")}},ub:function(a){var b;try{b=q.parse(m.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}var e=this.b.u?"":"&u="+encodeURIComponent(document.location.href);b.push(a.replace(/^https?:\/\//,"")+e);m.set("Hm_unsent_"+c.id,q.stringify(b))},
fb:function(a){var b;try{b=q.parse(m.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}if(b.length){a=a.replace(/^https?:\/\//,"");for(var e=0;e<b.length;e++)if(a.replace(/&u=[^&]*/,"")===b[e].replace(/&u=[^&]*/,"")){b.splice(e,1);break}b.length?m.set("Hm_unsent_"+c.id,q.stringify(b)):this.Qa()}},Qa:function(){m.remove("Hm_unsent_"+c.id)},uc:function(){var a=this,b;try{b=q.parse(m.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}if(b.length)for(var e=function(b){g.log(k.la+"//"+b,function(b){a.fb(b)})},f=0;f<
b.length;f++)e(b[f])},Ua:function(){return Math.round(+new Date/1E3)%65535}};return new a})();var B=h.z,C=h.load;c.pt&&C([B.protocol,"//ada.baidu.com/phone-tracker/insert_bdtj?sid=",c.pt].join(""));
(function(){var a=mt.g,b=mt.lang,g=mt.event,d=mt.o;if("undefined"!==typeof h.c&&(c.med||(!a.ga||7<a.Qb())&&c.cvcc)){var e,l,f,m,q=function(a){if(a.item){for(var b=a.length,d=Array(b);b--;)d[b]=a[b];return d}return[].slice.call(a)},t=function(a,b){for(var d in a)if(a.hasOwnProperty(d)&&b.call(a,d,a[d])===x)return x},r=function(a,g){var k={};k.n=e;k.t="clk";k.v=a;if(g){var l=g.getAttribute("href"),m=g.getAttribute("onclick")?""+g.getAttribute("onclick"):w,n=g.getAttribute("id")||"";f.test(l)?(k.sn=
"mediate",k.snv=l):b.d(m,"String")&&f.test(m)&&(k.sn="wrap",k.snv=m);k.id=n}h.c.b.et=86;h.c.b.ep=d.stringify(k);h.c.i();for(k=+new Date;400>=+new Date-k;);};if(c.med)l="/zoosnet",e="swt",f=/swt|zixun|call|chat|zoos|business|talk|kefu|openkf|online|\/LR\/Chatpre\.aspx/i,m={click:function(){for(var a=[],b=q(document.getElementsByTagName("a")),b=[].concat.apply(b,q(document.getElementsByTagName("area"))),b=[].concat.apply(b,q(document.getElementsByTagName("img"))),d,e,g=0,k=b.length;g<k;g++)d=b[g],e=
d.getAttribute("onclick"),d=d.getAttribute("href"),(f.test(e)||f.test(d))&&a.push(b[g]);return a}};else if(c.cvcc){l="/other-comm";e="other";f=c.cvcc.q||s;var n=c.cvcc.id||s;m={click:function(){for(var a=[],b=q(document.getElementsByTagName("a")),b=[].concat.apply(b,q(document.getElementsByTagName("area"))),b=[].concat.apply(b,q(document.getElementsByTagName("img"))),d,e,g,k=0,l=b.length;k<l;k++)d=b[k],f!==s?(e=d.getAttribute("onclick"),g=d.getAttribute("href"),n?(d=d.getAttribute("id"),(f.test(e)||
f.test(g)||n.test(d))&&a.push(b[k])):(f.test(e)||f.test(g))&&a.push(b[k])):n!==s&&(d=d.getAttribute("id"),n.test(d)&&a.push(b[k]));return a}}}if("undefined"!==typeof m&&"undefined"!==typeof f){var u;l+=/\/$/.test(l)?"":"/";var k=function(a,d){if(u===d)return r(l+a,d),x;if(b.d(d,"Array")||b.d(d,"NodeList"))for(var e=0,f=d.length;e<f;e++)if(u===d[e])return r(l+a+"/"+(e+1),d[e]),x};g.e(document,"mousedown",function(a){a=a||window.event;u=a.target||a.srcElement;var d={};for(t(m,function(a,e){d[a]=b.d(e,
"Function")?e():document.getElementById(e)});u&&u!==document&&t(d,k)!==x;)u=u.parentNode})}}})();(function(){var a=mt.f,b=mt.lang,g=mt.event,d=mt.o;if("undefined"!==typeof h.c&&b.d(c.cvcf,"Array")&&0<c.cvcf.length){var e={qb:function(){for(var b=c.cvcf.length,d,m=0;m<b;m++)(d=a.Ra(decodeURIComponent(c.cvcf[m])))&&g.e(d,"click",e.za())},za:function(){return function(){h.c.b.et=86;var a={n:"form",t:"clk"};a.id=this.id;h.c.b.ep=d.stringify(a);h.c.i()}}};a.eb(function(){e.qb()})}})();
(function(){var a=mt.event,b=mt.o;if(c.med&&"undefined"!==typeof h.c){var g={n:"anti",sb:0,kb:0,clk:0},d=function(){h.c.b.et=86;h.c.b.ep=b.stringify(g);h.c.i()};a.e(document,"click",function(){g.clk++});a.e(document,"keyup",function(){g.kb=1});a.e(window,"scroll",function(){g.sb++});a.e(window,"load",function(){setTimeout(d,5E3)})}})();})();
